spring:
  application:
    name: shift-control-enterprise
  config:
    import:
      - optional:file:${user.dir}/.env.properties
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
  security:
    oauth2.resourceserver.jwt:
      issuer-uri: http://localhost:8085
      jwk-set-uri: http://localhost:8085/oauth2/jwks

